### ISSUE TITLE
Calendar icon in the widget should display the current date

### ISSUE THREAD

**Issue by breversa** [adolfintel/Clock31#7]
Hello!
On my Samsung Galaxy S9 running /e/OS 1.13 (Android 10) and Neo Launcher (https://github.com/NeoApplications/Neo-Launcher), the calendar icon in the widget displays an arbitrary "17th of July" calendar icon (NOT like the screenshot here: https://github.com/adolfintel/Clock31), which I find a bit confusing.

It would be great it if could display the current date instead.

(I’m not sure if it’s a Clock31 issue, or an OS theme one.)

**Comment by adolfintel** [comment]
It's normal, the calendar icon in the widget comes from the emoji font used by your OS, while the app icon is a PNG.
